stages:
  - ingest

ingest_job:
  stage: ingest
  image: python:3.11-slim
  rules:
    - if: $TARGET_REPO_URL
  before_script:
    - apt-get update && apt-get install -y git build-essential curl zstd

    - curl -fsSL https://ollama.com/install.sh | sh
    - ollama serve > /dev/null 2>&1 &

    - sleep 10

    - ollama pull embeddinggemma

    - pip install -r requirements.txt
  script:
    - python cli.py
